package org.reader.constant;

public enum FeedElement {
    // RSS Elements..
    ROOT_ELEMENT, CHANNEL, TITLE, LINK, DESCRIPTION, LANGUAGE, ITEM, ITEM_TITLE,
    ITEM_GUID, ITEM_LINK, ITEM_DESCRIPTION, ITEM_DC_CREATOR,
    ITEM_DC_DATE, ITEM_PUB_DATE,

    // Atom Elements..
    FEED, ATOM_TITLE, ATOM_SUBTITLE, ATOM_LINK, ATOM_ID, ATOM_UPDATED, ENTRY, ENTRY_TITLE, ENTRY_LINK,
    ENTRY_UPDATED, ENTRY_ID, ENTRY_SUMMARY, ENTRY_CONTENT, ENTRY_AUTHOR, AUTHOR_NAME, ENTRY_THUMBNAIL,

    UNKNOWN;
}
